import type { ExhibitScene, TourChapter } from "./types";

export const exhibitScenes: ExhibitScene[] = [
  { id: "hexi-entry", order: 1, title: "河西入境", eyebrow: "河西走廊历史背景", layer: "practice", mapView: { center: [102.88, 38.25], zoom: 8.25, pitch: 38, bearing: -12 }, pointIds: ["arrival-minqin"], leadMediaId: "journey-sky", narration: "从凉州—武威进入河西走廊：古丝路打开跨区域交流通道，今天的实践沿绿带、农田与荒漠之间的变化抵达民勤。", sourceIds: ["hexi-history"] },
  { id: "water-oasis", order: 2, title: "水写绿洲", eyebrow: "石羊河下游的时间切片", layer: "water", mapView: { center: [103.27, 38.76], zoom: 8.25, pitch: 46, bearing: -8 }, pointIds: ["hongyashan-reservoir", "shiyang-system", "qingtu-lake"], leadMediaId: "desert-sunset", narration: "红崖山水库调蓄石羊河来水，生态输水推动青土湖水面与植被恢复，共同维系民勤绿洲水脉。", sourceIds: ["minqin-ecology", "system-restoration", "system-governance-2023", "oasis-control-model-2025", "shiyang-beautiful-river-2022", "shiyang-plan-2008", "qingtu-rebirth-2024"] },
  { id: "field-days", order: 3, title: "两日实践", eyebrow: "采摘观察 · 科普 · 传播 · 劳动 · 记录", layer: "practice", mapView: { center: [103.4966, 38.7362], zoom: 13.15, pitch: 48, bearing: -10 }, pointIds: ["desert-observation", "base-activity-center", "watering-practice"], leadMediaId: "fruit-picking", narration: "两日影像串联白刺果采摘观察、中暑预防主题科普、哈密瓜直播助农、公益林浇水维护与基地记录，留下从傍晚观察到清晨劳动的连续现场切片。", sourceIds: [] },
  { id: "science-industry", order: 4, title: "科技与沙产业", eyebrow: "科研与沙产业背景", layer: "herbs", mapView: { center: [103.28, 38.78], zoom: 8.65, pitch: 42, bearing: -5 }, pointIds: ["desert-botanical-garden", "cistanche-landscape", "planned-herbs"], leadMediaId: "berries-close", narration: "从公开资料扩展沙生植物园、新型治沙技术与梭梭—肉苁蓉链路；锁阳、板蓝根以‘项目计划关注’标签进入后续调研框架。", sourceIds: ["desert-garden", "desert-institute", "cistanche-industry", "oasis-control-model-2025", "desert-food-industry-2024", "sand-control-tech-2026"] },
  { id: "youth-guardians", order: 5, title: "青年守护", eyebrow: "一次实践进入长期维护", layer: "people", mapView: { center: [103.45, 38.82], zoom: 8.95, pitch: 48, bearing: -10 }, pointIds: ["zhong-lin"], leadMediaId: "volunteer-base", narration: "公开人物故事与团队劳动影像在兴隆村交汇。种树只是开始，补水、养护、记录与传播才构成长线行动。", sourceIds: ["minqin-volunteers", "minqin-base-report", "young-tree-planters-2025"] },
];

export const tourChapters: TourChapter[] = exhibitScenes;
