import type { MediaAsset } from "./types";
import { publicAsset } from "./public-assets";

const mediaCatalog: MediaAsset[] = [
  { id: "journey-sky", type: "image", src: "/media/2026-08-03/journey-sky.webp", alt: "列车窗外的田野、山地与云层", caption: "向河西走廊行进，地貌从农田渐入旱区。", capturedAt: "2026-08-03 12:52", featured: true },
  { id: "journey-village", type: "image", src: "/media/2026-08-03/journey-village.webp", alt: "列车窗外的河西村落与山地", caption: "窗外的聚落与山地，构成进入河西的第一重空间印象。", capturedAt: "2026-08-03 13:12", featured: false },
  { id: "road-video", type: "video", src: "/media/2026-08-03/road-to-minqin.mp4", poster: "/media/2026-08-03/journey-village.webp", alt: "驶向民勤的公路影像", caption: "从武威方向驶向民勤，绿带、农田与荒漠依次出现。", capturedAt: "2026-08-03 15:02", featured: true, durationSeconds: 4.114 },
  { id: "desert-sunset", type: "image", src: "/media/2026-08-03/desert-sunset.webp", alt: "傍晚荒漠地平线上的落日", caption: "落日前的荒漠观察，光线勾勒出植被与沙地的边界。", capturedAt: "2026-08-03 20:00", featured: true },
  { id: "berries-close", type: "image", src: "/media/2026-08-03/berries-close.webp", alt: "白刺植株红色果实的近景", caption: "近景可见白刺红色果实分布于枝条之间，周围裸露沙面与稀疏植被共同呈现采摘区域的现场生境。", capturedAt: "2026-08-03 20:23", featured: true },
  { id: "observation-video", type: "video", src: "/media/2026-08-03/desert-observation.mp4", poster: "/media/2026-08-03/berries-close.webp", alt: "团队观察白刺果植株的短视频", caption: "团队从形态、果实与周边生境开始建立白刺果观察记录。", capturedAt: "2026-08-03 20:05", featured: false, durationSeconds: 12.009 },
  { id: "twilight-field", type: "image", src: "/media/2026-08-03/twilight-field.webp", alt: "暮色中的荒漠与团队成员", caption: "一天实践结束前，团队继续采集环境与植物影像。", capturedAt: "2026-08-03 20:04", featured: false },
  { id: "night-flags", type: "image", src: "/media/2026-08-03/night-flags.webp", alt: "夜色中迎风飘扬的公益旗帜", caption: "荒漠基地的夜晚：公益旗帜与志愿者留下的记忆。", capturedAt: "2026-08-03 20:41", featured: false },
  { id: "dawn-desert", type: "image", src: "/media/2026-08-04/dawn-desert.webp", alt: "清晨的沙地与成排梭梭", caption: "清晨进入作业区域，观察苗木密度、风向与沙面状态。", capturedAt: "2026-08-04 07:52", featured: true },
  { id: "seedling", type: "image", src: "/media/2026-08-04/seedling.webp", alt: "沙地中的幼苗近景", caption: "水抵达根部，幼苗才能在高蒸发环境中继续生长。", capturedAt: "2026-08-04 08:11", featured: false },
  { id: "team-walk", type: "image", src: "/media/2026-08-04/team-walk.webp", alt: "团队携带工具走入公益林地", caption: "队员分组携带水管和工具进入林地，清晨的步行把供水点、作业区域与分散苗木连接起来。", capturedAt: "2026-08-04 08:10", featured: true },
  { id: "irrigation-line", type: "image", src: "/media/2026-08-04/irrigation-line.webp", alt: "团队在沙地上展开浇水管线", caption: "铺设水管、寻找根部、控制水量，是苗木养护的连续动作。", capturedAt: "2026-08-04 09:03", featured: true },
  { id: "irrigation-video", type: "video", src: "/media/2026-08-04/irrigation-arrival.mp4", poster: "/media/2026-08-04/irrigation-line.webp", alt: "水车抵达林地的短视频", caption: "水车抵达林地后，队员沿供水管线展开工具并分配作业位置，为分散苗木的连续浇水建立供水条件。", capturedAt: "2026-08-04 08:37", featured: false, durationSeconds: 14.007 },
  { id: "watering-video", type: "video", src: "/media/2026-08-04/watering-together.mp4", poster: "/media/2026-08-04/team-walk.webp", alt: "团队共同浇灌苗木的短视频", caption: "一次浇水看似简单，却是荒漠苗木长期维护中的关键环节。", capturedAt: "2026-08-04 08:37", featured: true, durationSeconds: 4.181 },
  { id: "banner-team", type: "image", src: "/media/2026-08-04/banner-team.webp", alt: "队员在荒漠中举起实践团旗帜", caption: "浇水作业期间，实践团在公益林现场留下集体记录；身后的沙地、苗木与管线构成当天劳动的真实环境。", capturedAt: "2026-08-04 09:06", featured: true },
  { id: "banner-landscape", type: "image", src: "/media/2026-08-04/banner-landscape.webp", alt: "实践团旗帜与广阔沙地", caption: "旗帜之外，是需要久久为功的荒漠生态治理。", capturedAt: "2026-08-04 09:02", featured: false },
  { id: "sand-traces", type: "image", src: "/media/2026-08-04/sand-traces.webp", alt: "沙面上的动物活动痕迹", caption: "沙面痕迹也是生态观察的一部分，记录环境中细微的生命活动。", capturedAt: "2026-08-04 09:11", featured: false },
  { id: "water-work", type: "image", src: "/media/2026-08-04/water-work.webp", alt: "队员为沙地苗木浇水", caption: "水沿着人工挖出的浅坑汇入根部，减少无效流失。", capturedAt: "2026-08-04 09:12", featured: false },
  { id: "volunteer-base", type: "image", src: "/media/2026-08-04/volunteer-base.webp", alt: "公益林基地里不同高校留下的手绘标牌", caption: "一块块手绘标牌，记录着跨越山海而来的青年志愿者。", capturedAt: "2026-08-04 10:35", featured: true },
  { id: "volunteer-signs", type: "image", src: "/media/2026-08-04/volunteer-signs.webp", alt: "沙地苗木旁的志愿者手绘牌", caption: "社会力量持续参与，是民勤治沙图景中的重要一层。", capturedAt: "2026-08-04 10:35", featured: false },
  { id: "fruit-sunset-team", type: "image", src: "/media/2026-08-03/fruit-sunset-team.webp", alt: "傍晚团队在白刺果采摘观察区域集合", caption: "落日前抵达观察区域，团队先记录沙地、植株与采集环境。", capturedAt: "2026-08-03 19:48", featured: false },
  { id: "fruit-picking", type: "image", src: "/media/2026-08-03/fruit-picking.webp", alt: "队员在白刺植株旁采摘红色果实", caption: "队员在沙地白刺植株旁进行采摘，先观察果实分布与枝条状态，再把采集过程纳入现场影像记录。", capturedAt: "2026-08-03 19:54", featured: true },
  { id: "fruit-bearing-shrub", type: "image", src: "/media/2026-08-03/fruit-bearing-shrub.webp", alt: "沙地中结有红色果实的灌木", caption: "从植株形态、果实分布和周边生境建立现场观察记录。", capturedAt: "2026-08-03 20:01", featured: true },
  { id: "fruit-collection", type: "image", src: "/media/2026-08-03/fruit-collection.webp", alt: "队员展示采集到的红色果实", caption: "队员展示采集到的红色果实，记录植株观察与采集过程。", capturedAt: "2026-08-03 20:05", featured: false },
  { id: "fruit-drying", type: "image", src: "/media/2026-08-03/fruit-drying.webp", alt: "采集后的果实在基地摊开整理", caption: "果实被带回基地摊开整理，构成从野外观察到后续记录的一环。", capturedAt: "2026-08-03 20:44", featured: false },
  { id: "fruit-field-video", type: "video", src: "/media/2026-08-03/fruit-field.mp4", poster: "/media/2026-08-03/fruit-sunset-team.webp", alt: "白刺果采摘观察现场短视频", caption: "傍晚采摘观察的连续画面，呈现沙地、植株与团队行动。", capturedAt: "2026-08-03 19:49", featured: false, durationSeconds: 4.972 },
  { id: "heat-science-presenter", type: "image", src: "/media/2026-08-03/heat-science-presenter.webp", alt: "队员在实践团旗帜前开展中暑预防主题科普", caption: "团队在基地开展中暑预防主题科普活动。", capturedAt: "2026-08-03 21:03", featured: true },
  { id: "heat-science-audience", type: "image", src: "/media/2026-08-03/heat-science-audience.webp", alt: "队员围坐参与中暑预防主题科普", caption: "队员围绕高温环境下的自我保护开展现场交流。", capturedAt: "2026-08-03 21:17", featured: false },
  { id: "heat-science-slides", type: "image", src: "/media/2026-08-03/heat-science-slides.webp", alt: "科普活动中队员结合屏幕进行说明", caption: "队员借助演示材料梳理高温环境下的自我保护要点，并通过讲解与互动把科普内容带入现场情境。", capturedAt: "2026-08-03 21:23", featured: false },
  { id: "heat-science-demo", type: "image", src: "/media/2026-08-03/heat-science-demo.webp", alt: "中暑预防主题科普中的互动演示", caption: "互动演示让夜间科普活动从讲解进入共同参与。", capturedAt: "2026-08-03 21:31", featured: false },
  { id: "heat-science-video", type: "video", src: "/media/2026-08-03/heat-science.mp4", poster: "/media/2026-08-03/heat-science-presenter.webp", alt: "中暑预防主题科普活动短视频", caption: "短视频记录队员讲解、演示与参与过程。", capturedAt: "2026-08-03 21:18", featured: false, durationSeconds: 14 },
  { id: "live-melon-still", type: "image", src: "/media/2026-08-03/live-melon-still.webp", alt: "直播助农活动中队员展示当地哈密瓜", caption: "团队通过经过隐私裁剪的直播画面介绍当地哈密瓜。", capturedAt: "2026-08-03", timeLabel: "8月3日深夜", featured: true },
  { id: "live-melon-video", type: "video", src: "/media/2026-08-03/live-melon.mp4", poster: "/media/2026-08-03/live-melon-still.webp", alt: "队员进行哈密瓜直播助农的隐私裁剪短视频", caption: "隐私裁剪后的短视频保留人物、哈密瓜与现场传播过程。", capturedAt: "2026-08-03", timeLabel: "8月3日深夜", featured: false, durationSeconds: 14 },
  { id: "watering-truck", type: "image", src: "/media/2026-08-04/watering-truck.webp", alt: "公益林浇水维护现场与供水车辆", caption: "清晨抵达维护区域，水源、管线和人员协作共同构成作业条件。", capturedAt: "2026-08-04 08:03", featured: false },
  { id: "watering-hose-team", type: "image", src: "/media/2026-08-04/watering-hose-team.webp", alt: "队员协作铺设浇水软管", caption: "队员分工展开水管，在沙地中寻找并连接待养护苗木。", capturedAt: "2026-08-04 08:13", featured: true },
  { id: "watering-field-walk", type: "image", src: "/media/2026-08-04/watering-field-walk.webp", alt: "队员穿行于公益林苗木之间", caption: "苗木分散在沙地中，浇水维护需要在较大范围内持续移动。", capturedAt: "2026-08-04 08:35", featured: false },
  { id: "watering-shrub-detail", type: "image", src: "/media/2026-08-04/watering-shrub-detail.webp", alt: "公益林苗木与根部浇水区域近景", caption: "近距离记录水分抵达根部及周边沙面状态。", capturedAt: "2026-08-04 09:09", featured: false },
  { id: "watering-action", type: "image", src: "/media/2026-08-04/watering-action.webp", alt: "队员在沙地中为苗木浇水", caption: "将水引向苗木根部，是一次次重复、具体的长期养护动作。", capturedAt: "2026-08-04 09:48", featured: true },
  { id: "water-flow-video", type: "video", src: "/media/2026-08-04/water-flow.mp4", poster: "/media/2026-08-04/watering-shrub-detail.webp", alt: "水流进入沙地苗木根部的短视频", caption: "水沿浅坑进入苗木根部，记录公益林日常维护的微观过程。", capturedAt: "2026-08-04 08:25", featured: false, durationSeconds: 14 },
  { id: "base-dune-installation", type: "image", src: "/media/2026-08-03/base-dune-installation.webp", alt: "公益林基地沙丘与公益装置全景", caption: "基地环境把沙丘、公益设施与长期志愿行动并置在同一空间中。", capturedAt: "2026-08-03 17:52", featured: true },
  { id: "volunteer-sign-field", type: "image", src: "/media/2026-08-04/volunteer-sign-field.webp", alt: "公益林基地中成片的志愿标牌", caption: "不同时间到来的志愿者留下标牌，也留下需要继续维护的责任。", capturedAt: "2026-08-04 10:37", featured: false },
  { id: "forest-technical-board", type: "image", src: "/media/2026-08-04/forest-technical-board.webp", alt: "基地内民勤县公益治沙造林技术规程展板", caption: "现场技术展板呈现公益治沙造林的规范化要求，作为基地环境记录展示。", capturedAt: "2026-08-04 16:22", featured: false },
  { id: "sunset-flags-base", type: "image", src: "/media/2026-08-04/sunset-flags-base.webp", alt: "夕阳下的沙丘、公益旗帜与基地设施", caption: "夕阳把两日实践收束到基地环境：一次活动结束，长期维护仍在继续。", capturedAt: "2026-08-04 19:31", featured: true },
];

export const media: MediaAsset[] = mediaCatalog.map((asset) => ({
  ...asset,
  src: publicAsset(asset.src),
  poster: asset.poster ? publicAsset(asset.poster) : undefined,
}));
