import type { HerbProfile, RelationshipEdge } from "./types";
import { publicAsset } from "./public-assets";

export const herbs: HerbProfile[] = [
  {
    id: "licorice",
    name: "甘草",
    latinLabel: "Glycyrrhiza uralensis",
    tag: "根系药材",
    evidenceLabel: "公开资料可核",
    description: "2020年公开资料记录：民勤县大坝镇420亩三年生甘草进入机械辅助采收，根部经翻犁后由人工拣收。",
    descriptionEn: "A 2020 field report records 420 mu of three-year-old licorice harvested in Daba Town, Minqin.",
    sourceIds: ["minqin-herb-harvest-2020", "desert-garden"],
    mapPointId: "desert-botanical-garden",
    image: {
      src: publicAsset("/media/resources/licorice.jpg"),
      alt: "甘草植株与羽状复叶",
      caption: "甘草植株（Glycyrrhiza uralensis）",
      credit: "Daderot · Wikimedia Commons",
      license: "CC0",
      sourceUrl: "https://commons.wikimedia.org/wiki/File:Glycyrrhiza_uralensis_-_Chelsea_Physic_Garden_-_DSC02839.jpg",
    },
    facts: [
      { label: "种植记录", value: "420亩" },
      { label: "生长年限", value: "3年生" },
      { label: "资料地点", value: "大坝镇" },
    ],
    sections: {
      habitat: "国家中医药管理局转载的2020年现场资料把甘草种植点明确到民勤县大坝镇，展示的是县域栽培基地，而非未定位的荒漠野生植株。",
      ecology: "页面以根系和生长年限为观察重点：报道中的基地甘草均为三年生，采收对象是地下根部。",
      cultivation: "2020年大坝镇甘草基地记录面积为420亩。该数字对应报道当年、该基地，不外推为今天的全县规模。",
      harvest: "现场先割除地上茎枝，再用拖拉机牵引犁铧约30厘米深翻；工人随后用四齿耙拣出甘草根。",
      processing: "报道呈现了收获、挑选、晾晒与销售的连续环节；本展签将其作为从田间根材进入初加工的真实链路。",
      communication: "核心数据来自2020年12月4日公开报道；物种图为甘草图鉴照片，与民勤基地采收照片分开标注。",
    },
  },
  {
    id: "cistanche",
    name: "肉苁蓉",
    latinLabel: "Cistanche deserticola",
    tag: "梭梭寄生植物",
    evidenceLabel: "公开资料可核",
    description: "青土湖资料记录梭梭林接种肉苁蓉的生态产业路径：固沙寄主与地下寄生植物在同一基地协同培育。",
    descriptionEn: "At Qingtu Lake, cistanche cultivation is documented beneath planted Haloxylon forest as an ecological industry chain.",
    sourceIds: ["minqin-herb-harvest-2020", "cistanche-industry", "desert-food-industry-2024"],
    mapPointId: "cistanche-landscape",
    image: {
      src: publicAsset("/media/resources/cistanche.jpg"),
      alt: "荒漠中抽生的肉苁蓉花序",
      caption: "肉苁蓉（Cistanche deserticola），摄于新疆鄯善",
      credit: "Anagoria · Wikimedia Commons",
      license: "CC BY 3.0",
      sourceUrl: "https://commons.wikimedia.org/wiki/File:2017-07-22_Cistanche_deserticola_anagoria.jpg",
    },
    facts: [
      { label: "梭梭林记录", value: "约4600亩" },
      { label: "寄主关系", value: "梭梭根系" },
      { label: "资料地点", value: "青土湖" },
    ],
    sections: {
      habitat: "2020年资料记录青土湖肉苁蓉基地位于近4600亩人工梭梭林中；这里的观察单位不是单株药材，而是梭梭林与地下寄生植物共同组成的沙地系统。",
      ecology: "梭梭承担防风固沙和生境营造功能，肉苁蓉寄生于其根部。公开资料据此把生态修复与资源利用连接为一条生态—产业链。",
      cultivation: "资料记载基地已完成4600亩接种，其中620亩用于肉苁蓉种子培育；这些数字均标注为2020年报道记录。",
      harvest: "报道中的采收画面为工人两人一组挖土、抛沙，寻找地下肉苁蓉；展示不以循环视频或示意图替代这一真实过程。",
      processing: "当期资料记录年采挖量115吨、优质种子153公斤，反映原料与种子繁育两条链路，不等同于当前产量。",
      communication: "展签同时列出政府资料、生态产业资料和物种照片授权；面积、产量与影像拍摄地分别注明，避免混写。",
    },
  },
  {
    id: "cynomorium",
    name: "锁阳",
    latinLabel: "Cynomorium songaricum",
    tag: "荒漠寄生植物",
    evidenceLabel: "公开资料可核",
    description: "中科院植物资料明确记录锁阳分布于甘肃民勤；《植物学报》研究还把民勤纳入河西走廊野生居群采样点。",
    descriptionEn: "CAS records Cynomorium songaricum in Minqin; a botanical study also sampled a wild Minqin population.",
    sourceIds: ["cynomorium-cas", "cynomorium-genetics-2018"],
    mapPointId: "planned-herbs",
    image: {
      src: publicAsset("/media/resources/cynomorium.jpg"),
      alt: "荒漠地表抽生的红棕色锁阳花序",
      caption: "锁阳（Cynomorium songaricum），摄于哈萨克斯坦",
      credit: "Alexander Dubynin · Wikimedia Commons",
      license: "CC BY 4.0",
      sourceUrl: "https://commons.wikimedia.org/wiki/File:Cynomorium_songaricum_424460009.jpg",
    },
    facts: [
      { label: "民勤记录", value: "明确分布" },
      { label: "研究样本", value: "18居群 / 188株" },
      { label: "典型寄主", value: "白刺等" },
    ],
    sections: {
      habitat: "中科院资料记录锁阳生于荒漠草原、草原化荒漠与荒漠地带的河边、湖边、池边等生境，也见于具有寄主植物的盐碱地。",
      ecology: "锁阳是无叶绿素的多年生肉质寄生草本，多数植株埋在沙中；其寄主包括白刺、骆驼蓬和霸王等荒漠植物。",
      cultivation: "公开资料首先确认的是民勤野生分布与寄主关系。《植物学报》研究把民勤列为18个野生居群之一，而不是把它描述成普通田作物基地。",
      harvest: "2018年研究分析河西走廊与青海18个野生居群、188个个体，并指出现存居群呈近期生境片段化特征，资源展示因此同时关注保护。",
      processing: "该研究利用ITS序列识别7个变异位点和9个单倍型，为锁阳的系统分类、资源鉴定与保护措施提供分子证据。",
      communication: "本页的民勤分布来自中科院资料，样本数据来自《植物学报》；照片摄于哈萨克斯坦，仅用于展示可核物种形态。",
    },
  },
  {
    id: "isatis",
    name: "板蓝根",
    latinLabel: "Isatis indigotica",
    tag: "栽培根类药材",
    evidenceLabel: "公开资料可核",
    description: "2020年公开资料记录民勤县双茨科镇连片种植400亩板蓝根，并使用移苗定植、田间管理与机械采收。",
    descriptionEn: "A 2020 report documents a contiguous 400-mu Isatis field and mechanized harvest in Shuangcike Town, Minqin.",
    sourceIds: ["minqin-herb-harvest-2020"],
    mapPointId: "planned-herbs",
    image: {
      src: publicAsset("/media/resources/isatis.jpg"),
      alt: "开黄色小花的菘蓝植株",
      caption: "菘蓝（Isatis indigotica），其根入药称板蓝根",
      credit: "阿橋 HQ · Wikimedia Commons",
      license: "CC BY-SA 2.0",
      sourceUrl: "https://commons.wikimedia.org/wiki/File:菘藍_Isatis_indigotica_-香港花展_Hong_Kong_Flower_Show-_(9216111022).jpg",
    },
    facts: [
      { label: "种植记录", value: "400亩" },
      { label: "采收方式", value: "两台收割机" },
      { label: "资料地点", value: "双茨科镇" },
    ],
    sections: {
      habitat: "公开报道把板蓝根种植点明确到民勤县双茨科镇，记录的是连片栽培田，而非把它笼统归入荒漠野生植物。",
      ecology: "板蓝根是菘蓝的干燥根。展签用开花植株照片连接地上形态与地下根材，便于理解“植物名—药材名”的关系。",
      cultivation: "2020年双茨科镇基地连片种植400亩，报道明确提到移苗定植技术与后期田间管理。",
      harvest: "报道现场有两台收割机在田间作业，工人随后捡拾板蓝根，呈现机械起挖与人工整理配合的采收方式。",
      processing: "当年资料记录收获后的药材进入挑选、晾晒和销售环节，板蓝根主要销往河北、河南等地。",
      communication: "400亩与销售方向均来自2020年报道，只代表当年资料快照；物种照片展示的是菘蓝植株，不替代基地现场影像。",
    },
  },
];

export const relationshipEdges: RelationshipEdge[] = [
  { id: "relation-water-forest", fromPointId: "shiyang-system", toPointId: "watering-practice", label: "水 → 养护", explanation: "流域治理提供理解背景，团队劳动落在公益林补水与长期养护。" },
  { id: "relation-haloxylon-cistanche", fromPointId: "desert-botanical-garden", toPointId: "cistanche-landscape", label: "固沙 → 沙产业", explanation: "梭梭的生态功能与肉苁蓉资源利用形成公开资料中的生态—产业关系。" },
  { id: "relation-science-governance", fromPointId: "desert-research-institute", toPointId: "shiyang-system", label: "科研 → 治理", explanation: "长期观测与技术研究为系统治理提供知识与方法支撑。" },
  { id: "relation-governance-youth", fromPointId: "shiyang-system", toPointId: "zhong-lin", label: "治理 → 青年参与", explanation: "社会力量通过种植、补水、养护和传播进入长期治理过程。" },
];
