import type { HerbProfile, RelationshipEdge } from "./types";

export const herbs: HerbProfile[] = [
  { id: "licorice", name: "甘草", latinLabel: "Glycyrrhiza spp.", tag: "耐旱资源", evidenceLabel: "公开资料可核", description: "项目关注的民勤特色资源之一。首期从生境、资源与初加工角度介绍，不延伸到个体用药。", descriptionEn: "A drought-adapted medicinal resource introduced through habitat and responsible processing.", sourceIds: ["desert-garden"], mapPointId: "desert-botanical-garden", sections: { habitat: "耐旱、耐盐碱的荒漠及半荒漠生境是理解甘草资源的入口。", ecology: "作为多年生植物资源，可从根系、生境适应和资源保护角度观察。", cultivation: "首期只介绍规范化种植的概念，不声明团队已调查具体种植基地。", harvest: "采收信息应结合品种、年限和规范要求，页面不提供操作处方。", processing: "以清理、分级和初加工链路作产业示意，不对应具体企业。", communication: "传播内容限定为资源文化与产业知识，不延伸至个人用药。" } },
  { id: "cistanche", name: "肉苁蓉", latinLabel: "Cistanche spp.", tag: "沙产业", evidenceLabel: "公开资料可核", description: "公开资料呈现肉苁蓉与梭梭固沙、沙产业之间的生态—产业联系。", descriptionEn: "A desert resource connecting ecological restoration with a responsible local value chain.", sourceIds: ["cistanche-industry", "desert-food-industry-2024"], mapPointId: "cistanche-landscape", sections: { habitat: "荒漠环境中的寄生型植物资源，与寄主植物共同构成观察单元。", ecology: "梭梭承担固沙与生境功能，肉苁蓉资源利用形成生态—产业联系。", cultivation: "展示寄主建立与资源培育的关系，不提供具体技术参数。", harvest: "采收作为产业链阶段呈现，不将公开概述写成团队实访结论。", processing: "由原料进入分级和初加工环节，具体企业数据不在首期范围。", communication: "强调治沙与产业协同，不作功效承诺或产品推荐。" } },
  { id: "cynomorium", name: "锁阳", latinLabel: "Cynomorium songaricum", tag: "荒漠生境", evidenceLabel: "项目计划关注", description: "属于项目计划的关注对象。首期不表述为团队已实地鉴定或当地已规模生产。", descriptionEn: "A planned research focus, not a claim of completed field identification or local production.", sourceIds: [], mapPointId: "planned-herbs", sections: { habitat: "项目计划关注荒漠寄生植物的生境适应，目前没有团队鉴定记录。", ecology: "只作为生态关系的待调研问题，不映射为本次现场观察植物。", cultivation: "首期没有可核验的团队种植调查，保留为后续访谈提纲。", harvest: "未取得本地采收资料，不展示产量、规模或操作细节。", processing: "仅保留产业链位置，等待后续公开资料或实地材料补充。", communication: "明确标记为项目计划关注，避免把研究设想写成完成成果。" } },
  { id: "isatis", name: "板蓝根", latinLabel: "Isatis indigotica", tag: "种植链路", evidenceLabel: "项目计划关注", description: "属于项目计划的关注对象，可作为种植—采收—加工—传播链路的内容框架。", descriptionEn: "A project-scope crop used to frame a responsible production and communication chain.", sourceIds: [], mapPointId: "planned-herbs", sections: { habitat: "作为栽培药用资源纳入项目计划，首期不声称在荒漠现场完成鉴定。", ecology: "与典型荒漠寄生资源分开展示，避免混淆生态类型。", cultivation: "可用于说明规范种植管理的内容框架，尚无团队基地调研数据。", harvest: "采收环节作为计划中的产业问题，不提供具体时间和产量。", processing: "初加工、产品和质量传播构成后续可补充的研究链路。", communication: "只作资源和产业介绍，不提供医疗建议。" } },
];

export const relationshipEdges: RelationshipEdge[] = [
  { id: "relation-water-forest", fromPointId: "shiyang-system", toPointId: "watering-practice", label: "水 → 养护", explanation: "流域治理提供理解背景，团队劳动落在公益林补水与长期养护。" },
  { id: "relation-haloxylon-cistanche", fromPointId: "desert-botanical-garden", toPointId: "cistanche-landscape", label: "固沙 → 沙产业", explanation: "梭梭的生态功能与肉苁蓉资源利用形成公开资料中的生态—产业关系。" },
  { id: "relation-science-governance", fromPointId: "desert-research-institute", toPointId: "shiyang-system", label: "科研 → 治理", explanation: "长期观测与技术研究为系统治理提供知识与方法支撑。" },
  { id: "relation-governance-youth", fromPointId: "shiyang-system", toPointId: "zhong-lin", label: "治理 → 青年参与", explanation: "社会力量通过种植、补水、养护和传播进入长期治理过程。" },
];
