import type { SourceRef } from "./types";

export const sources: SourceRef[] = [
  { id: "hexi-history", publisher: "丝绸之路（敦煌）国际文化博览会", title: "一条河西走廊，何以串起千年文明？", url: "https://www.gswbj.gov.cn/a/2023/09/21/18697.html", publishedAt: "2023-09-21", kind: "government", topics: ["河西走廊", "丝绸之路"], summary: "河西走廊连接中原与西域，凉州（今武威）位于走廊东端，为团队进入民勤的路线补充历史与空间背景。" },
  { id: "minqin-ecology", publisher: "国家林业和草原局", title: "民勤：漠上绿洲生生不息", url: "https://www.forestry.gov.cn/c/www/xxgcjqdxal/513785.jhtml", publishedAt: "2023-07-12", kind: "government", topics: ["青土湖", "生态输水", "治沙"], summary: "资料记录青土湖1959年干涸、2010年重新形成约3平方公里水面，以及2023年的水域面积数据，呈现尾闾湖逐步恢复的时间过程。" },
  { id: "system-restoration", publisher: "国家林业和草原局", title: "民勤系统治沙与石羊河流域治理实践", url: "https://www.forestry.gov.cn/c/www/xxgcjqdxal/547094.jhtml", publishedAt: "公开资料", kind: "government", topics: ["石羊河", "系统治理"], summary: "石羊河流域治理把农业节水、生态输水、固沙造林和植被修复纳入同一体系，说明治水与治沙需要协同推进。" },
  { id: "desert-garden", publisher: "国家林业和草原局", title: "甘肃民勤沙生植物园守护荒漠植物资源", url: "https://www.forestry.gov.cn/lyj/1/lhgzdt/20260611/675938.html", publishedAt: "2026-06-11", kind: "government", topics: ["沙生植物", "种质资源", "科研"], summary: "民勤沙生植物园长期保存荒漠植物资源，并承担科研监测与科普展示，使沙生植物从治理对象转化为可持续观察和保护的资源。" },
  { id: "desert-institute", publisher: "国家林业和草原局", title: "甘肃省治沙研究所民勤治沙研究", url: "https://www.forestry.gov.cn/c/www/sbjs/586525.jhtml", publishedAt: "公开资料", kind: "research", topics: ["治沙科研", "长期观测"], summary: "甘肃省治沙研究所在民勤持续开展荒漠化监测、材料试验与技术研究，长期观测让治理措施能够依据环境变化不断调整。" },
  { id: "minqin-volunteers", publisher: "人民网甘肃频道", title: "‘请到民勤种棵树’，缘何吸引数万青年志愿者", url: "https://gs.people.com.cn/BIG5/n2/2026/0508/c358184-41574026.html", publishedAt: "2026-05-08", kind: "media", topics: ["青年志愿者", "公益治沙"], summary: "报道呈现青年志愿者从种植到补水、养护的持续参与，说明公益治沙不是一次活动，而是需要长期返回和共同维护的行动。" },
  { id: "minqin-base-report", publisher: "国家林业和草原局（来源：新华网）", title: "跨越山海种树护绿", url: "https://www.forestry.gov.cn/lyj/1/dfdt/20260423/668473.html", publishedAt: "2026-04-23", kind: "media", topics: ["公益林", "青年行动"], summary: "报道记录不同地区青年进入民勤参与公益林建设，也强调树木成活依赖后续补水和养护，把跨地域参与与长期责任联系起来。" },
  { id: "cistanche-industry", publisher: "中国生态文明网", title: "民勤梭梭—肉苁蓉生态沙产业资料", url: "https://www.eco.gov.cn/news_info/28258.html", publishedAt: "公开资料", kind: "organization", topics: ["梭梭", "肉苁蓉", "沙产业"], summary: "梭梭承担防风固沙和生境营造作用，肉苁蓉资源利用由此进入沙产业链，形成生态修复与产业收益相互连接的路径。" },
  { id: "system-governance-2023", publisher: "国家林业和草原局", title: "民勤治沙走进系统治理的高质量发展阶段", url: "https://www.forestry.gov.cn/c/www/lhgzdt/525542.jhtml", publishedAt: "2023-09-27", kind: "government", topics: ["系统治理", "青土湖", "三北工程"], summary: "民勤治沙由单一阻沙工程逐步转向流域调水、植被恢复和环绿洲锁边协同推进，治理对象从局部沙丘扩展到完整生态系统。" },
  { id: "oasis-control-model-2025", publisher: "国家林业和草原局", title: "甘肃民勤绿洲治沙模式", url: "https://www.forestry.gov.cn/c/www/lhgzdt/629877.jhtml", publishedAt: "2025-06-11", kind: "government", topics: ["环绿洲锁边", "系统治理", "生态屏障"], summary: "民勤按照绿洲外围不同风沙条件分区施策，通过锁边林草带、工程固沙和科技手段共同构建保护绿洲的生态屏障。" },
  { id: "shiyang-beautiful-river-2022", publisher: "生态环境部", title: "石羊河（武威段）", url: "https://www.mee.gov.cn/home/ztbd/2021/mlhhyxalzjhd/tmal/202201/t20220127_968348.shtml", publishedAt: "2022-01-24", kind: "government", topics: ["石羊河", "河湖治理", "生态恢复"], summary: "石羊河武威段把水库调蓄、河道治理和下游生态恢复连接起来，展示从红崖山水库到青土湖的流域治理链条。" },
  { id: "shiyang-plan-2008", publisher: "国家发展和改革委员会", title: "国务院批复石羊河流域治理规划", url: "https://www.ndrc.gov.cn/fzggw/jgsj/ghs/sjdt/200802/t20080229_1169770.html", publishedAt: "2008-02-29", kind: "government", topics: ["石羊河", "治理规划", "政策"], summary: "国务院批复的流域治理规划确立了节水、生态恢复和用水结构调整等综合措施，为后续石羊河重点治理提供政策起点。" },
  { id: "qingtu-rebirth-2024", publisher: "国家林业和草原局（来源：光明网）", title: "‘三北’工程攻坚战｜甘肃青土湖：沙漠湖泊‘重生记’", url: "https://www.forestry.gov.cn/lyj/1/xxbd/20240529/565322.html", publishedAt: "2024-05-29", kind: "media", topics: ["青土湖", "生态输水", "三北工程"], summary: "报道回溯青土湖从1959年干涸到2010年重新出现水面的变化，并把生态输水、植被恢复与尾闾湖重生联系起来。" },
  { id: "young-tree-planters-2025", publisher: "人民网", title: "一群年轻人，去民勤种树", url: "http://society.people.com.cn/n1/2025/0516/c428181-40480841.html", publishedAt: "2025-05-16", kind: "media", topics: ["兴隆村", "青年志愿者", "公益林"], summary: "报道聚焦兴隆村青年种树行动，也呈现苗木补水、复访和养护等后续工作，让志愿参与从一次种植延伸为长期守护。" },
  { id: "desert-food-industry-2024", publisher: "国家林业和草原局三北局", title: "向沙地要食物，实现绿富共赢", url: "https://www.forestry.gov.cn/c/sbj/stcy/584857.jhtml", publishedAt: "2024-09-09", kind: "government", topics: ["梭梭", "肉苁蓉", "生态产业"], summary: "资料介绍在梭梭林中发展肉苁蓉资源利用的实践，说明防风固沙、生境建设与产业增收可以在同一沙地系统中协同。" },
  { id: "sand-control-tech-2026", publisher: "国家林业和草原局（来源：人民日报）", title: "甘肃民勤县治理荒漠化用上新技术", url: "https://www.forestry.gov.cn/lyj/1/jdyw/20260714/680553.html", publishedAt: "2026-07-14", kind: "media", topics: ["治沙技术", "科研", "荒漠化治理"], summary: "报道展示新型治沙材料、现场试验与科研成果转化，说明民勤治沙正在把长期经验与可验证的新技术结合起来。" },
];
