import type { StoryPoint } from "./types";

export const storyPoints: StoryPoint[] = [
  { id: "arrival-minqin", layer: "practice", title: "从河西进入民勤", eyebrow: "实践足迹 · 起点", coordinates: [103.0938, 38.6247], accuracy: "县域叙事点", locationNote: "以民勤县城作为入境叙事中心，不代表照片拍摄坐标。", date: "2026.08.03", contentOrigin: "团队实践", evidenceStatus: "团队影像记录", tourChapter: "hexi-entry", summary: "从武威方向进入民勤，团队记录沿途聚落、农田、绿带与荒漠之间的快速转换。", summaryEn: "The journey into Minqin reveals a rapid transition from settlements and farmland to shelterbelts and desert.", mediaIds: ["journey-sky", "journey-village", "road-video"], sourceIds: [], color: "#d95c3d" },
  { id: "desert-observation", layer: "practice", title: "白刺果采摘观察（名称待专业核验）", eyebrow: "实践足迹 · 采摘观察", coordinates: [103.493175, 38.740369], accuracy: "GPS实拍点", locationNote: "坐标为8月3日影像 EXIF 样本中心，仅表示拍摄区域；不是入口或导航坐标。‘白刺果’名称来自团队素材目录，尚待专业核验。", date: "2026.08.03", contentOrigin: "团队实践", evidenceStatus: "团队影像记录", tourChapter: "field-days", summary: "团队记录沙地植株、红色果实、采摘和整理过程。页面保留名称核验边界，不进行药材鉴定或功效说明。", summaryEn: "The team documented fruit picking and habitat conditions; the plant name remains pending expert verification.", mediaIds: ["desert-sunset", "berries-close", "observation-video", "twilight-field", "fruit-sunset-team", "fruit-picking", "fruit-bearing-shrub", "fruit-collection", "fruit-drying", "fruit-field-video"], sourceIds: [], color: "#cf7c3a" },
  { id: "base-activity-center", layer: "practice", title: "公益林基地：三项现场证据", eyebrow: "实践足迹 · 同一地点，多项行动", coordinates: [103.500018, 38.73236], accuracy: "GPS实拍点", locationNote: "坐标为基地环境影像 EXIF 样本中心，仅表示团队拍摄区域；三项记录共用这一经核验的拍摄区域，不拆分为未经核验的新点位，也不据此推断行政村归属或基地边界。", date: "2026.08.03—04", contentOrigin: "团队实践", evidenceStatus: "团队影像记录", tourChapter: "field-days", summary: "同一基地坐标串联中暑预防科普、直播助农尝试，以及志愿基地与治沙技术展板记录，现场影像按三条证据线索展开。", summaryEn: "One verified base location connects three documented activities: heat-safety education, digital support for local produce, and evidence of volunteer and sand-control practices.", mediaIds: ["base-dune-installation", "heat-science-presenter", "heat-science-audience", "heat-science-slides", "heat-science-demo", "heat-science-video", "live-melon-still", "live-melon-video", "night-flags", "volunteer-sign-field", "forest-technical-board", "sunset-flags-base"], evidenceGroups: [
    { id: "heat-prevention-education", label: "01 · 科普记录", title: "中暑预防科普", summary: "团队在高温荒漠实践环境中组织夜间主题讲解、演示与现场交流，照片和视频记录了讲解者、参与者及演示材料。", boundary: "仅呈现活动过程，不构成医学诊断、治疗或用药建议。", mediaIds: ["heat-science-presenter", "heat-science-audience", "heat-science-slides", "heat-science-demo", "heat-science-video"] },
    { id: "live-aid-attempt", label: "02 · 数字传播", title: "直播助农尝试", summary: "团队通过直播画面介绍当地西瓜，把现场实践延伸到数字传播与助农尝试。", boundary: "发布素材经过隐私裁剪，不展示账号、评论、订单、销量或平台数据。", mediaIds: ["live-melon-still", "live-melon-video"] },
    { id: "volunteer-base-evidence", label: "03 · 基地证据", title: "志愿基地与治沙技术证据", summary: "基地沙丘、公益装置、志愿标牌和治沙造林技术规程展板，共同记录长期志愿参与与现场技术环境。", boundary: "展板与标牌只证明现场可见内容，不据此虚构培训经历、人物归属或基地边界。", mediaIds: ["base-dune-installation", "night-flags", "volunteer-sign-field", "forest-technical-board", "sunset-flags-base"] },
  ], sourceIds: [], color: "#b84d3b" },
  { id: "watering-practice", layer: "practice", title: "公益林浇水维护", eyebrow: "实践足迹 · 公益林养护", coordinates: [103.493172, 38.731853], accuracy: "GPS实拍点", locationNote: "坐标为8月4日影像 EXIF 样本中心，仅表示作业拍摄区域；不是基地入口、行政边界或导航坐标。", date: "2026.08.04", contentOrigin: "团队实践", evidenceStatus: "团队影像记录", tourChapter: "field-days", summary: "团队在公益林开展水管铺设、苗木浇水、沙面观察和影像记录。GPS 采样线只反映部分拍摄点，不构成完整移动轨迹。", summaryEn: "The team laid hoses, watered seedlings and documented the forest; GPS samples represent capture locations, not a complete route.", mediaIds: ["dawn-desert", "seedling", "team-walk", "irrigation-line", "irrigation-video", "watering-video", "banner-team", "banner-landscape", "sand-traces", "water-work", "watering-truck", "watering-hose-team", "watering-field-walk", "watering-shrub-detail", "watering-action", "water-flow-video"], sourceIds: [], color: "#2f7658" },
  { id: "qingtu-lake", layer: "water", title: "青土湖：绿洲的晴雨表", eyebrow: "绿洲水脉 · 尾闾湖", coordinates: [103.56, 39.12], accuracy: "公开知识点", locationNote: "依据公开地理资料标示尾闾湖区域，仅用于知识浏览。", date: "1959—2023", contentOrigin: "公开资料", evidenceStatus: "公开资料可核", tourChapter: "water-oasis", summary: "青土湖是石羊河尾闾湖。公开资料记录1959年完全干涸、2010年恢复约3平方公里水面，2023年报道水域面积27.65平方公里；数字均保留对应年份。", summaryEn: "Qingtu Lake records the oasis' recovery through dated public figures rather than a live statistic.", mediaIds: [], sourceIds: ["minqin-ecology", "system-restoration", "system-governance-2023", "qingtu-rebirth-2024"], color: "#228aa1" },
  { id: "hongyashan-reservoir", layer: "water", title: "红崖山水库", eyebrow: "绿洲水脉 · 调蓄", coordinates: [103.04, 38.42], accuracy: "公开知识点", locationNote: "公开地理知识点；水脉线为叙事示意，不是河道测绘或导航路线。", date: "公开资料", contentOrigin: "公开资料", evidenceStatus: "公开资料可核", tourChapter: "water-oasis", summary: "红崖山水库及石羊河下游生态输水，是理解民勤‘治沙先治水’的重要入口。", summaryEn: "Hongyashan Reservoir and ecological water releases are central to understanding restoration in the lower Shiyang River basin.", mediaIds: [], sourceIds: ["minqin-ecology", "system-restoration", "shiyang-beautiful-river-2022"], color: "#228aa1" },
  { id: "shiyang-system", layer: "water", title: "石羊河系统治理", eyebrow: "绿洲水脉 · 流域", coordinates: [103.20, 38.70], accuracy: "公开知识点", locationNote: "县域尺度的流域治理叙事点，不表示单项工程位置。", date: "2007—至今", contentOrigin: "公开资料", evidenceStatus: "公开资料可核", tourChapter: "water-oasis", summary: "节水、生态输水、固沙造林与植被修复共同构成系统治理，政策规划、河湖治理与环绿洲锁边在同一流域框架中衔接。", summaryEn: "Water saving, ecological releases, shelterbelts and vegetation recovery form an integrated restoration system.", mediaIds: [], sourceIds: ["system-restoration", "system-governance-2023", "oasis-control-model-2025", "shiyang-beautiful-river-2022", "shiyang-plan-2008"], color: "#228aa1" },
  { id: "desert-botanical-garden", layer: "herbs", title: "民勤沙生植物园", eyebrow: "药材产业 · 资源保育", coordinates: [103.12, 38.68], accuracy: "公开知识点", locationNote: "县域图示点位，访问前请以机构公开地址为准。", date: "1974—2026", contentOrigin: "公开资料", evidenceStatus: "公开资料可核", tourChapter: "science-industry", summary: "公开资料介绍，民勤沙生植物园长期开展荒漠植物资源保存、科研监测与科普工作，是理解沙生植物资源的重要知识节点。", summaryEn: "The Minqin Desert Botanical Garden supports conservation, research and public education around desert plant resources.", mediaIds: [], sourceIds: ["desert-garden", "desert-institute"], color: "#9b7b2f" },
  { id: "cistanche-landscape", layer: "herbs", title: "梭梭—肉苁蓉沙产业", eyebrow: "药材产业 · 生态链路", coordinates: [103.48, 38.91], accuracy: "公开知识点", locationNote: "县域产业知识点，不代表某一企业、基地或团队到访位置。", date: "公开资料", contentOrigin: "公开资料", evidenceStatus: "公开资料可核", tourChapter: "science-industry", summary: "公开资料将梭梭固沙与肉苁蓉资源利用联系起来，形成生态修复与资源产业协同的观察线索。", summaryEn: "Public sources connect Haloxylon shelterbelts with Cistanche cultivation as an ecological desert-industry model.", mediaIds: [], sourceIds: ["cistanche-industry", "desert-food-industry-2024"], color: "#9b7b2f" },
  { id: "planned-herbs", layer: "herbs", title: "项目计划关注药材", eyebrow: "药材产业 · 内容边界", coordinates: [103.0938, 38.6247], accuracy: "公开知识点", locationNote: "内容索引点，不表示种植基地或团队走访位置。", date: "2026项目计划", contentOrigin: "项目计划", evidenceStatus: "项目计划关注", tourChapter: "science-industry", summary: "甘草、肉苁蓉、锁阳和板蓝根来自项目计划的关注范围。锁阳与板蓝根不在首期中表述为团队已调查或当地规模生产。", summaryEn: "Four herbs belong to the project scope; the first release does not imply completed fieldwork or scaled local production for every item.", mediaIds: ["berries-close"], sourceIds: [], color: "#9b7b2f" },
  { id: "desert-research-institute", layer: "people", title: "甘肃省治沙研究所", eyebrow: "人物故事 · 科技支撑", coordinates: [103.10, 38.64], accuracy: "公开知识点", locationNote: "县域知识点，用于呈现长期科研与监测网络，不作为到访记录。", date: "公开资料", contentOrigin: "公开资料", evidenceStatus: "公开资料可核", tourChapter: "science-industry", summary: "公开资料显示，科研人员在民勤长期开展荒漠化监测、治沙材料试验与技术研究，为当地生态治理提供持续的科技支撑。", summaryEn: "Long-term field monitoring and desertification research provide scientific support for restoration in Minqin.", mediaIds: [], sourceIds: ["desert-institute", "sand-control-tech-2026"], color: "#7a3f34" },
  { id: "zhong-lin", layer: "people", title: "仲麟与青年公益治沙", eyebrow: "人物故事 · 公开资料", coordinates: [103.59, 38.88], accuracy: "村级近似定位", locationNote: "公开报道定位至收成镇兴隆村；非人物住址、非精确基地坐标。", date: "2023—2026", contentOrigin: "公开资料", evidenceStatus: "公开资料可核", tourChapter: "youth-guardians", summary: "公开报道记载，仲麟返乡投身公益治沙，并在兴隆村组织志愿种树与后续养护。", summaryEn: "Public reporting documents Zhong Lin's return to Minqin and continued volunteer planting and maintenance work.", mediaIds: ["volunteer-base", "volunteer-signs", "watering-video"], sourceIds: ["minqin-volunteers", "minqin-base-report", "young-tree-planters-2025"], color: "#7a3f34" },
];
